language: node_js
matrix:
  include:
    - node_js: "lts/*"
    - node_js: 14
    - node_js: 12
    - node_js: 10
  allow_failures:
    - node_js: "lts/*"
    - node_js: 10
before_install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get -y update
  - sudo apt-get -y install python3.9
  - sudo update-alternatives --config python3
  - python3 -V
install:
  - npm install
  - npm install --only=dev
script:
  - npm test
  - npm run coverage
  - npm run build
cache:
  directories:
  - "node_modules"
branches:
  only:
  - master
  - develop
  - alpha
  - beta
